### PR TITLE
Added CMake install targets

### PR DESCRIPTION
**Pull request by omaralvarez**
I added CMake install target so that a user can:

```bash
mkdir build
cd build
cmake ..
make install
```
Next, you can use:

```cmake
find_package(croncpp REQUIRED)
```
And in the code:

```cpp
#include <croncpp/croncpp.h>
```

### CODE REVIEW

**Comment by mariusbancila** [comment]
I can't merge this as it breaks the building for the test and benchmark projects.

**Comment by omaralvarez** [comment]
They compiled for me. What problem are you having?

**Comment by mariusbancila** [comment]
What I did was:

```
git checkout -b omaralvarez-master master
git pull https://github.com/omaralvarez/croncpp.git master
mkdir build
cd build
cmake ..\benchmark
```

Then loaded and build the project:

> fatal error C1083: Cannot open include file: 'croncpp.h': No such file or directory

**Comment by omaralvarez** [comment]
Could you try:

```
cmake ..
```

**Pull request closed without merging**
